### ISSUE TITLE
version of JanusGraph

### ISSUE THREAD

**Issue by suesunss** [marcelocf/janusgraph_tutorial#5]
hello,

which version of JanusGraph does this project use?

**Comment by Bentipe** [comment]
If you look at the start_janus.sh you can see that is using the version 0.1.0

> JANUS_VERSION=0.1.0

https://github.com/marcelocf/janusgraph_tutorial/blob/master/start_janus.sh

**Comment by suesunss** [comment]
@Bentipe got it, thanks!
